on:
  release:
    types: [published]

name: Publish Package

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: make Cargo.toml
      - run: cargo install cargo-unleash --git https://github.com/xlc/cargo-unleash.git # https://github.com/paritytech/cargo-unleash/pull/38
      - run: cargo unleash em-dragons
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
