name: Zepter

on:
  pull_request:
    branches:
      - master
      - polkadot-**
    paths-ignore:
      - '**/README.md'
  push:
    branches:
      - master
      - polkadot-**
    paths-ignore:
      - '**/README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@nightly
    - name: Install Zepter
      run: cargo install zepter --version 0.15.0 --locked -q -f --no-default-features && zepter --version
    - run: |
        make Cargo.toml
        cargo update
        cargo update base64ct --precise 1.6.0 # 1.8.0 requires the Cargo feature called `edition2024`
    - name: Check Rust features
      run: make dev-features-check
